# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 11b2e8d78664dc1f8e989a5340d929a844492896  # frozen: v1.48.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 6e2418c5521b7d606e72914dced3253f9ace1205  # frozen: v3.4.0
  hooks:
    - id: check-yaml
